#!/bin/bash

export GITHUB_TOKEN=${PLUGIN_GITHUB_TOKEN}

echo "Cloning ksonnet repo.."
hub clone "${PLUGIN_GITHUB_ORG}/${PLUGIN_GITHUB_REPO}" repo

cd repo || exit

echo "Create branch for PR..."
git checkout -b "${DRONE_BRANCH}/${PLUGIN_TAG}"

echo "Updating ${PLUGIN_KS_COMPONENT} image for environment ${PLUGIN_KS_ENV}"
ks param set "${PLUGIN_KS_COMPONENT}" \
  "${PLUGIN_REPO}:${PLUGIN_TAG}" \
  --env "${PLUGIN_KS_ENV}"

git add environments/.

echo "Commit changes..."
git commit -m "Drone auto-upgrade: ${PLUGIN_KS_COMPONENT} to ${PLUGIN_TAG}"

echo "Pushing branch"
hub push origin "${DRONE_BRANCH}/${PLUGIN_TAG}"

echo "Creating Pull Request..."

hub pull-request \
  -m "${DRONE_REPO_NAME} ${PLUGIN_TAG}\n${PLUGIN_REPO}:${PLUGIN_TAG}\nGenerated by Drone"

echo "DONE!!!"
