#!/bin/bash
set -e

env

git config --global user.email "drone@drone.io"
git config --global user.name "drone"

echo "Cloning ksonnet repo.."
git clone "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${PLUGIN_GITHUB_ORG}/${PLUGIN_GITHUB_REPO}.git"

cd "${PLUGIN_GITHUB_REPO}"

echo "Create branch for PR..."
git checkout -b "${DRONE_BRANCH}/${PLUGIN_TAG}"

echo "Updating ${PLUGIN_KS_COMPONENT} image for environment ${PLUGIN_KS_ENV}"
ks param set "${PLUGIN_KS_COMPONENT}" \
  "${PLUGIN_DOCKER_REPO}:${PLUGIN_TAG}" \
  --env "${PLUGIN_KS_ENV}"

git add environments/.

echo "Commit changes..."
git commit -m "Drone auto-upgrade: ${PLUGIN_KS_COMPONENT} to ${PLUGIN_TAG}"

echo "Pushing branch"
hub push origin "${DRONE_BRANCH}/${PLUGIN_TAG}"

echo "Creating Pull Request..."

hub pull-request \
  -m "${DRONE_REPO_NAME} ${PLUGIN_TAG}
${PLUGIN_DOCKER_REPO}:${PLUGIN_TAG}
Generated by Drone"

echo "DONE!!!"
